"""create table birds

Revision ID: 176ef1da7336
Revises: 
Create Date: 2024-06-16 21:22:37.288051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '176ef1da7336'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('birds')
    # ### end Alembic commands ###
